// Generado por scripts/generar_datos.py desde marcas-app-backend. No editar a mano.

export const VERSION_DEL_FILTRO = "multi_v8";

export const PESO_GENERICA = 0.6;

export const PALABRAS_VACIAS = new Set<string>(["a", "agency", "al", "an", "and", "at", "bakery", "bazar", "beauty", "brand", "brands", "by", "cia", "club", "co", "company", "con", "connect", "coop", "cooperativa", "corp", "corporation", "data", "de", "deco", "del", "design", "distribuidor", "distribuidora", "e", "el", "en", "entertainment", "es", "estilo", "estudio", "events", "feria", "for", "gestion", "group", "grupo", "hay", "holding", "holdings", "home", "in", "inc", "inmobiliaria", "inmobiliario", "integral", "juridico", "la", "lab", "labs", "las", "le", "les", "llc", "lo", "los", "ltd", "ltda", "management", "marcas", "market", "marketing", "mas", "mi", "mis", "my", "más", "natural", "nos", "o", "of", "on", "or", "our", "para", "pet", "pets", "por", "que", "real", "sa", "saci", "saic", "sas", "se", "services", "servicios", "shop", "si", "sin", "sl", "sll", "son", "srl", "ssa", "store", "stream", "studio", "studios", "su", "sus", "te", "team", "the", "tienda", "to", "travel", "travels", "tu", "tus", "u", "un", "una", "unas", "unos", "viaje", "viajes", "vos", "y", "ya", "your"]);

export const PALABRAS_GENERICAS = new Set<string>(["accesorios", "acsibi", "agro", "agua", "aires", "alimentos", "alma", "amigo", "animal", "app", "arena", "arg", "argentina", "argentino", "aromas", "arquitectura", "art", "arte", "artesanal", "artesanales", "aura", "bar", "bien", "bienestar", "black", "boca", "boutique", "box", "buenos", "burger", "cafe", "capital", "care", "casa", "centro", "champaqui", "ciudad", "coffee", "com", "consultora", "copa", "corazon", "cordoba", "desarrollos", "desde", "digital", "disenyo", "distrito", "don", "dulce", "energia", "energy", "entre", "escuela", "esencia", "espacio", "estetica", "eventos", "expo", "express", "fabrica", "familia", "festival", "fiesta", "finca", "fino", "fit", "fitness", "fleibor", "fleigel", "frisvy", "fundacion", "futbol", "global", "gran", "hidroflux", "hogar", "house", "indumentaria", "industria", "industrial", "ingenieria", "inmobiliarios", "instituto", "inteligente", "internacional", "island", "joyas", "legal", "life", "loopha", "lotba", "luna", "luz", "mar", "maria", "mate", "max", "mercado", "metodo", "mini", "movimiento", "mundial", "mundo", "norte", "nova", "nuestro", "one", "origen", "oro", "padel", "pan", "paso", "pass", "pastas", "pasteleria", "pilates", "pizza", "plata", "poceada", "poceadita", "power", "pro", "prode", "producciones", "propiedades", "punto", "qiankun", "raiz", "red", "rhode", "risd", "rosario", "sabor", "sabores", "salud", "san", "santa", "school", "segunda", "seguridad", "seguros", "ser", "siempre", "skin", "smart", "sol", "soluciones", "solutions", "somos", "sport", "sur", "sushi", "tech", "tecnologia", "todo", "turismo", "urban", "vida", "vision", "vital", "vtl", "wine", "world", "yerba", "zona"]);
